// Comprehensive AI LLM Provider Database for NeoGateway
// Excludes: aion, cloudflare-ai, cohere, gemini, kilo-gateway, mistral, nvidia, openrouter, sambanova, siliconflow, deepseek

export interface ProviderData {
  name: string;
  slug: string;
  category: string;
  region: string;
  baseUrl: string;
  apiFormat: string;
  authType: string;
  authHeader: string;
  keyPrefix: string;
  modelsUrl: string;
  docsUrl: string;
  pricing: string;
  freeTier: boolean;
  status: string;
  notes: string;
  models: {
    modelId: string;
    modelName: string;
    contextWindow: number | null;
    maxOutput: number | null;
    pricing: string;
    capabilities: string[];
  }[];
}

export const providers: ProviderData[] = [
  // ===== FIRST-PARTY PROVIDERS =====
  {
    name: "OpenAI",
    slug: "openai",
    category: "first-party",
    region: "us",
    baseUrl: "https://api.openai.com/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "sk-",
    modelsUrl: "https://api.openai.com/v1/models",
    docsUrl: "https://platform.openai.com/docs",
    pricing: '{"gpt-4.1":{"input":"$2/mtok","output":"$8/mtok"},"gpt-4.1-mini":{"input":"$0.4/mtok","output":"$1.6/mtok"},"gpt-4.1-nano":{"input":"$0.1/mtok","output":"$0.4/mtok"},"o3":{"input":"$2/mtok","output":"$8/mtok"},"o4-mini":{"input":"$1.1/mtok","output":"$4.4/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "Tier-based free credits. GPT-5.5, o3, o4-mini latest. Supports Assistants API, function calling, structured outputs.",
    models: [
      { modelId: "gpt-4.1", modelName: "GPT-4.1", contextWindow: 1047576, maxOutput: 32768, pricing: "$2/$8 per Mtok", capabilities: ["chat", "vision", "function_calling"] },
      { modelId: "gpt-4.1-mini", modelName: "GPT-4.1 Mini", contextWindow: 1047576, maxOutput: 32768, pricing: "$0.4/$1.6 per Mtok", capabilities: ["chat", "vision", "function_calling"] },
      { modelId: "gpt-4.1-nano", modelName: "GPT-4.1 Nano", contextWindow: 1047576, maxOutput: 32768, pricing: "$0.1/$0.4 per Mtok", capabilities: ["chat", "vision"] },
      { modelId: "o3", modelName: "o3", contextWindow: 200000, maxOutput: 100000, pricing: "$2/$8 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "o4-mini", modelName: "o4-mini", contextWindow: 200000, maxOutput: 100000, pricing: "$1.1/$4.4 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "gpt-4o", modelName: "GPT-4o", contextWindow: 128000, maxOutput: 16384, pricing: "$2.5/$10 per Mtok", capabilities: ["chat", "vision", "function_calling"] },
    ]
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    category: "first-party",
    region: "us",
    baseUrl: "https://api.anthropic.com/v1",
    apiFormat: "anthropic",
    authType: "header",
    authHeader: "x-api-key",
    keyPrefix: "sk-ant-",
    modelsUrl: "",
    docsUrl: "https://docs.anthropic.com",
    pricing: '{"claude-opus-4":{"input":"$15/mtok","output":"$75/mtok"},"claude-sonnet-4":{"input":"$3/mtok","output":"$15/mtok"},"claude-haiku-3.5":{"input":"$0.8/mtok","output":"$4/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "Claude Opus 4.8, Sonnet 4, Haiku 3.5. Supports extended thinking, tool use, computer use, PDF vision. $5 free credits.",
    models: [
      { modelId: "claude-opus-4-20250514", modelName: "Claude Opus 4", contextWindow: 200000, maxOutput: 32000, pricing: "$15/$75 per Mtok", capabilities: ["chat", "vision", "function_calling"] },
      { modelId: "claude-sonnet-4-20250514", modelName: "Claude Sonnet 4", contextWindow: 200000, maxOutput: 64000, pricing: "$3/$15 per Mtok", capabilities: ["chat", "vision", "function_calling"] },
      { modelId: "claude-haiku-3.5-20241022", modelName: "Claude Haiku 3.5", contextWindow: 200000, maxOutput: 8192, pricing: "$0.8/$4 per Mtok", capabilities: ["chat", "vision", "function_calling"] },
    ]
  },
  {
    name: "xAI",
    slug: "xai",
    category: "first-party",
    region: "us",
    baseUrl: "https://api.x.ai/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "xai-",
    modelsUrl: "https://api.x.ai/v1/models",
    docsUrl: "https://docs.x.ai/docs",
    pricing: '{"grok-3":{"input":"$3/mtok","output":"$15/mtok"},"grok-3-mini":{"input":"$0.3/mtok","output":"$0.5/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "Grok 3, Grok 3 Mini. OpenAI-compatible API. Free tier available. Image generation via Aurora.",
    models: [
      { modelId: "grok-3", modelName: "Grok 3", contextWindow: 131072, maxOutput: 16384, pricing: "$3/$15 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "grok-3-mini", modelName: "Grok 3 Mini", contextWindow: 131072, maxOutput: 16384, pricing: "$0.3/$0.5 per Mtok", capabilities: ["chat", "function_calling"] },
    ]
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    category: "first-party",
    region: "us",
    baseUrl: "https://api.perplexity.ai",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "pplx-",
    modelsUrl: "",
    docsUrl: "https://docs.perplexity.ai",
    pricing: '{"sonar-pro":{"input":"$3/mtok","output":"$15/mtok"},"sonar":{"input":"$1/mtok","output":"$1/mtok"}}',
    freeTier: false,
    status: "active",
    notes: "Search-augmented LLM. pplx- API prefix. Supports online search, citations. Sonar and Sonar Pro models.",
    models: [
      { modelId: "sonar-pro", modelName: "Sonar Pro", contextWindow: 200000, maxOutput: 8192, pricing: "$3/$15 per Mtok", capabilities: ["chat", "search"] },
      { modelId: "sonar", modelName: "Sonar", contextWindow: 127000, maxOutput: 8192, pricing: "$1/$1 per Mtok", capabilities: ["chat", "search"] },
    ]
  },
  {
    name: "AI21 Labs",
    slug: "ai21",
    category: "first-party",
    region: "global",
    baseUrl: "https://api.ai21.com/studio/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.ai21.com",
    pricing: '{"jamba-1.5-large":{"input":"$2/mtok","output":"$8/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "Jamba 1.5 Large (SSM+Transformer hybrid). Free tier available. Supports long context.",
    models: [
      { modelId: "jamba-1.5-large", modelName: "Jamba 1.5 Large", contextWindow: 256000, maxOutput: 8192, pricing: "$2/$8 per Mtok", capabilities: ["chat", "function_calling"] },
    ]
  },

  // ===== INFERENCE PROVIDERS =====
  {
    name: "Together AI",
    slug: "together",
    category: "inference",
    region: "us",
    baseUrl: "https://api.together.xyz/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "https://api.together.xyz/v1/models",
    docsUrl: "https://docs.together.ai",
    pricing: '{"meta-llama-3.1-405b":{"input":"$0.8/mtok","output":"$0.8/mtok"},"Qwen/Qwen2.5-72B":{"input":"$0.4/mtok","output":"$0.4/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "200+ open-source models. SFT, DPO, LoRA fine-tuning. GPU clusters. Serverless inference. $25 free credits.",
    models: [
      { modelId: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo", modelName: "Llama 3.1 405B", contextWindow: 131072, maxOutput: 8192, pricing: "$0.8/$0.8 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "Qwen/Qwen2.5-72B-Instruct-Turbo", modelName: "Qwen 2.5 72B", contextWindow: 131072, maxOutput: 8192, pricing: "$0.4/$0.4 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "deepseek-ai/DeepSeek-R1", modelName: "DeepSeek R1", contextWindow: 131072, maxOutput: 8192, pricing: "$0.8/$0.8 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "Fireworks AI",
    slug: "fireworks",
    category: "inference",
    region: "us",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "fw_",
    modelsUrl: "https://api.fireworks.ai/inference/v1/models",
    docsUrl: "https://docs.fireworks.ai",
    pricing: '{"llama-v3p1-405b":{"input":"$0.8/mtok","output":"$0.8/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "Full post-training stack (SFT, RLHF, DPO). Fast inference engine. LoRA fine-tuning. Image gen (Stable Diffusion).",
    models: [
      { modelId: "accounts/fireworks/models/llama-v3p1-405b-instruct", modelName: "Llama 3.1 405B", contextWindow: 131072, maxOutput: 16384, pricing: "$0.8/$0.8 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "accounts/fireworks/models/llama4-maverick-instruct-basic", modelName: "Llama 4 Maverick", contextWindow: 131072, maxOutput: 16384, pricing: "$0.2/$0.2 per Mtok", capabilities: ["chat", "vision", "function_calling"] },
    ]
  },
  {
    name: "Groq",
    slug: "groq",
    category: "inference",
    region: "us",
    baseUrl: "https://api.groq.com/openai/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "gsk_",
    modelsUrl: "https://api.groq.com/openai/v1/models",
    docsUrl: "https://console.groq.com/docs",
    pricing: '{"llama-3.3-70b":{"input":"$0.59/mtok","output":"$0.79/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "LPUs (Language Processing Units). Ultra-low latency (<200ms). Free tier: 30 req/min, 14400 tok/day. Llama, Mixtral, Gemma.",
    models: [
      { modelId: "llama-3.3-70b-versatile", modelName: "Llama 3.3 70B", contextWindow: 131072, maxOutput: 32768, pricing: "$0.59/$0.79 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "llama-3.1-8b-instant", modelName: "Llama 3.1 8B", contextWindow: 131072, maxOutput: 8192, pricing: "$0.05/$0.08 per Mtok", capabilities: ["chat"] },
      { modelId: "mixtral-8x7b-32768", modelName: "Mixtral 8x7B", contextWindow: 32768, maxOutput: 8192, pricing: "$0.24/$0.24 per Mtok", capabilities: ["chat", "function_calling"] },
    ]
  },
  {
    name: "Cerebras",
    slug: "cerebras",
    category: "inference",
    region: "us",
    baseUrl: "https://api.cerebras.ai/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "csk-",
    modelsUrl: "",
    docsUrl: "https://docs.cerebras.ai",
    pricing: '{"llama-3.3-70b":{"input":"$0.85/mtok","output":"$1.20/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "Wafer-Scale Engine (WSE-3). Fastest inference chip. Free tier available. Llama 3.3 70B @ ~1800 tok/s.",
    models: [
      { modelId: "llama-3.3-70b", modelName: "Llama 3.3 70B", contextWindow: 131072, maxOutput: 8192, pricing: "$0.85/$1.20 per Mtok", capabilities: ["chat"] },
      { modelId: "llama3.1-8b", modelName: "Llama 3.1 8B", contextWindow: 8192, maxOutput: 4096, pricing: "$0.10/$0.10 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "Hyperbolic",
    slug: "hyperbolic",
    category: "inference",
    region: "us",
    baseUrl: "https://api.hyperbolic.xyz/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.hyperbolic.xyz",
    pricing: '{"llama-3.1-8b":{"input":"$0.05/mtok","output":"$0.05/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "Cheap inference. Supports text + image gen. Game-focused AI. Very competitive pricing.",
    models: [
      { modelId: "meta-llama/Llama-3.1-8B-Instruct", modelName: "Llama 3.1 8B", contextWindow: 131072, maxOutput: 4096, pricing: "$0.05/$0.05 per Mtok", capabilities: ["chat"] },
      { modelId: "meta-llama/Llama-3.1-70B-Instruct", modelName: "Llama 3.1 70B", contextWindow: 131072, maxOutput: 4096, pricing: "$0.4/$0.4 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "Novita AI",
    slug: "novita",
    category: "inference",
    region: "us",
    baseUrl: "https://api.novita.ai/v3/openai",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.novita.ai",
    pricing: '{"llama-3.1-8b":{"input":"$0.05/mtok","output":"$0.05/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "Budget-friendly. Text + image generation. Large model catalog. Pay-as-you-go.",
    models: [
      { modelId: "meta-llama/llama-3.1-8b-instruct", modelName: "Llama 3.1 8B", contextWindow: 8192, maxOutput: 4096, pricing: "$0.05/$0.05 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "Chutes AI",
    slug: "chutes",
    category: "inference",
    region: "us",
    baseUrl: "https://chutes.ai/api",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.chutes.ai",
    pricing: '{}',
    freeTier: true,
    status: "active",
    notes: "Free/inexpensive LLM inference. Multiple model support. Community-focused.",
    models: [
      { modelId: "llama-3.1-8b", modelName: "Llama 3.1 8B", contextWindow: 8192, maxOutput: 4096, pricing: "Free tier", capabilities: ["chat"] },
    ]
  },
  {
    name: "Lepton AI",
    slug: "lepton",
    category: "inference",
    region: "us",
    baseUrl: "https://llama2-7b.lepton.run/api/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.lepton.ai",
    pricing: '{}',
    freeTier: true,
    status: "active",
    notes: "Quick deploy open-source models. Serverless GPU. Simple API. Some free endpoints.",
    models: [
      { modelId: "llama2-7b", modelName: "Llama 2 7B", contextWindow: 4096, maxOutput: 2048, pricing: "Free tier available", capabilities: ["chat"] },
    ]
  },
  {
    name: "Inference.net",
    slug: "inference-dot-net",
    category: "inference",
    region: "us",
    baseUrl: "https://api.inference.net/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://inference.net",
    pricing: '{}',
    freeTier: false,
    status: "active",
    notes: "High-performance inference. Recommended by SiliconFlow as top 5 open-source LLM provider.",
    models: [
      { modelId: "meta-llama/Llama-3.1-70B-Instruct", modelName: "Llama 3.1 70B", contextWindow: 131072, maxOutput: 8192, pricing: "Contact for pricing", capabilities: ["chat"] },
    ]
  },

  // ===== GATEWAY / ROUTER PROVIDERS =====
  {
    name: "Portkey",
    slug: "portkey",
    category: "gateway",
    region: "us",
    baseUrl: "https://api.portkey.ai/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.portkey.ai",
    pricing: "Pay-per-use via underlying providers",
    freeTier: true,
    status: "active",
    notes: "Unified gateway for 250+ models. Observability, guardrails, caching, load balancing. OpenAI-compatible.",
    models: [
      { modelId: "openai/gpt-4.1", modelName: "GPT-4.1 (via Portkey)", contextWindow: 1047576, maxOutput: 32768, pricing: "Pass-through", capabilities: ["chat", "vision", "function_calling"] },
    ]
  },
  {
    name: "Braintrust",
    slug: "braintrust",
    category: "gateway",
    region: "us",
    baseUrl: "https://api.braintrust.dev/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://www.braintrust.dev/docs",
    pricing: "Pay-per-use via underlying providers",
    freeTier: true,
    status: "active",
    notes: "AI gateway with prompt playground, evaluations, logging. Supports 100+ providers. Open-source.",
    models: [
      { modelId: "gpt-4.1", modelName: "GPT-4.1 (via Braintrust)", contextWindow: 1047576, maxOutput: 32768, pricing: "Pass-through", capabilities: ["chat", "vision"] },
    ]
  },
  {
    name: "Vercel AI Gateway",
    slug: "vercel-ai-gateway",
    category: "gateway",
    region: "us",
    baseUrl: "https://gateway.ai.vercel.sh/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://vercel.com/docs/ai-gateway",
    pricing: "Free tier + usage-based",
    freeTier: true,
    status: "active",
    notes: "Edge-based AI gateway. Caching, rate limiting, logging, fallbacks. Works with Vercel deployments.",
    models: [
      { modelId: "openai/gpt-4.1", modelName: "GPT-4.1 (via Vercel)", contextWindow: 1047576, maxOutput: 32768, pricing: "Vercel pricing", capabilities: ["chat"] },
    ]
  },
  {
    name: "LiteLLM",
    slug: "litellm",
    category: "gateway",
    region: "us",
    baseUrl: "http://localhost:4000/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.litellm.ai",
    pricing: "Open-source (self-hosted)",
    freeTier: true,
    status: "active",
    notes: "27K+ GitHub stars. 140+ providers, 2600+ models. Open-source proxy. Load balancing, budget tracking, guardrails.",
    models: [
      { modelId: "*", modelName: "Any model via LiteLLM", contextWindow: null, maxOutput: null, pricing: "Self-hosted", capabilities: ["chat", "vision", "function_calling"] },
    ]
  },
  {
    name: "Helicone",
    slug: "helicone",
    category: "gateway",
    region: "us",
    baseUrl: "https://oai.helicone.ai/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.helicone.ai",
    pricing: "Free tier + usage-based",
    freeTier: true,
    status: "active",
    notes: "LLM observability + gateway. Request logging, cost tracking, prompt management, caching.",
    models: [
      { modelId: "openai/gpt-4.1", modelName: "GPT-4.1 (via Helicone)", contextWindow: 1047576, maxOutput: 32768, pricing: "Pass-through", capabilities: ["chat"] },
    ]
  },
  {
    name: "Mozilla any-llm",
    slug: "mozilla-any-llm",
    category: "gateway",
    region: "us",
    baseUrl: "",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://blog.mozilla.ai/introducing-any-llm",
    pricing: "Open-source (self-hosted)",
    freeTier: true,
    status: "active",
    notes: "Mozilla's unified LLM API. Open-source. Access any LLM provider through one interface.",
    models: []
  },

  // ===== CLOUD PROVIDERS =====
  {
    name: "Amazon Bedrock",
    slug: "aws-bedrock",
    category: "cloud",
    region: "us",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
    apiFormat: "custom",
    authType: "header",
    authHeader: "x-api-key",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.aws.amazon.com/bedrock",
    pricing: "Varies by model (Claude, Llama, Titan, Mistral, Cohere)",
    freeTier: true,
    status: "active",
    notes: "Claude, Llama, Titan, Mistral, Cohere, AI21. AWS IAM auth. On-demand + provisioned throughput. Cross-region inference.",
    models: [
      { modelId: "anthropic.claude-opus-4-20250514-v1:0", modelName: "Claude Opus 4 (Bedrock)", contextWindow: 200000, maxOutput: 32000, pricing: "$15/$75 per Mtok", capabilities: ["chat", "vision"] },
      { modelId: "meta.llama3-1-405b-instruct-v1:0", modelName: "Llama 3.1 405B (Bedrock)", contextWindow: 131072, maxOutput: 8192, pricing: "$3.0/$3.0 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "Azure OpenAI",
    slug: "azure-openai",
    category: "cloud",
    region: "global",
    baseUrl: "https://{resource}.openai.azure.com/openai/deployments/{deployment}",
    apiFormat: "openai",
    authType: "header",
    authHeader: "api-key",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://learn.microsoft.com/azure/ai/services/openai",
    pricing: "Azure pricing (varies by region)",
    freeTier: false,
    status: "active",
    notes: "GPT-4o, GPT-4.1, o-series on Azure. Enterprise security, VNET, Private Link. PTU pricing.",
    models: [
      { modelId: "gpt-4.1", modelName: "GPT-4.1 (Azure)", contextWindow: 1047576, maxOutput: 32768, pricing: "Azure pricing", capabilities: ["chat", "vision"] },
    ]
  },
  {
    name: "Google Vertex AI",
    slug: "vertex-ai",
    category: "cloud",
    region: "global",
    baseUrl: "https://{region}-aiplatform.googleapis.com/v1/projects/{project}/locations/{region}/publishers/google/models",
    apiFormat: "google",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://cloud.google.com/vertex-ai/docs",
    pricing: "GCP pricing (varies by region)",
    freeTier: true,
    status: "active",
    notes: "Gemini, Claude, Llama on GCP. Enterprise features, VPC-SC, model garden. $300 free credits.",
    models: [
      { modelId: "gemini-2.5-pro", modelName: "Gemini 2.5 Pro (Vertex)", contextWindow: 1048576, maxOutput: 65536, pricing: "$1.25/$10 per Mtok", capabilities: ["chat", "vision", "function_calling"] },
    ]
  },
  {
    name: "IBM watsonx",
    slug: "ibm-watsonx",
    category: "cloud",
    region: "us",
    baseUrl: "https://{region}.ml.cloud.ibm.com/ml/v1/deployments/{deployment}/text/generation",
    apiFormat: "custom",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://www.ibm.com/docs/en/watsonx-ai",
    pricing: "IBM Cloud pricing",
    freeTier: true,
    status: "active",
    notes: "Llama, Mistral, Granite models. Enterprise-grade. Regulatory compliance. On-prem option.",
    models: [
      { modelId: "meta-llama/llama-3-70b-instruct", modelName: "Llama 3 70B (watsonx)", contextWindow: 8192, maxOutput: 2048, pricing: "IBM pricing", capabilities: ["chat"] },
    ]
  },
  {
    name: "Databricks",
    slug: "databricks",
    category: "cloud",
    region: "us",
    baseUrl: "https://{workspace}.databricks.com/serving-endpoints",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "dapi",
    modelsUrl: "",
    docsUrl: "https://docs.databricks.com/en/mlops/foundation-models",
    pricing: "DBU-based pricing",
    freeTier: false,
    status: "active",
    notes: "DBRX, Llama, Mistral, Granite. MLflow integration. Feature stores. Delta Lake.",
    models: [
      { modelId: "dbrx-instruct", modelName: "DBRX Instruct", contextWindow: 32768, maxOutput: 4096, pricing: "DBU pricing", capabilities: ["chat", "function_calling"] },
    ]
  },
  {
    name: "Snowflake Cortex",
    slug: "snowflake-cortex",
    category: "cloud",
    region: "us",
    baseUrl: "https://{account}.snowflakecomputing.com/api/v2/cortex/inference:complete",
    apiFormat: "custom",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.snowflake.com/en/user-guide/snowflake-cortex",
    pricing: "Snowflake consumption-based",
    freeTier: false,
    status: "active",
    notes: "Mistral, Llama, Reka, Granite inside Snowflake. SQL-native AI. Data governance built-in.",
    models: [
      { modelId: "llama3.1-70b", modelName: "Llama 3.1 70B (Cortex)", contextWindow: 131072, maxOutput: 4096, pricing: "Snowflake credits", capabilities: ["chat"] },
    ]
  },

  // ===== MODEL HOSTING =====
  {
    name: "Hugging Face",
    slug: "huggingface",
    category: "hosting",
    region: "global",
    baseUrl: "https://api-inference.huggingface.co/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "hf_",
    modelsUrl: "",
    docsUrl: "https://huggingface.co/docs/api-inference",
    pricing: "Pay-per-use + Inference Endpoints ($0.06/hr+)",
    freeTier: true,
    status: "active",
    notes: "500K+ models. Inference Endpoints (dedicated/managed). Serverless Inference. Free tier for popular models.",
    models: [
      { modelId: "meta-llama/Meta-Llama-3.1-70B-Instruct", modelName: "Llama 3.1 70B", contextWindow: 131072, maxOutput: 8192, pricing: "$0.8/$0.8 per Mtok", capabilities: ["chat"] },
      { modelId: "mistralai/Mixtral-8x7B-Instruct-v0.1", modelName: "Mixtral 8x7B", contextWindow: 32768, maxOutput: 4096, pricing: "$0.24/$0.24 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "Replicate",
    slug: "replicate",
    category: "hosting",
    region: "us",
    baseUrl: "https://api.replicate.com/v1",
    apiFormat: "custom",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "r8_",
    modelsUrl: "",
    docsUrl: "https://replicate.com/docs",
    pricing: "Pay-per-prediction + dedicated hardware",
    freeTier: false,
    status: "active",
    notes: "Simple API for open-source models. Auto-scaling. Deploy custom models. Wide model marketplace.",
    models: [
      { modelId: "meta/llama-2-70b-chat", modelName: "Llama 2 70B Chat", contextWindow: 4096, maxOutput: 2048, pricing: "$0.65/$0.65 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "Modal",
    slug: "modal",
    category: "hosting",
    region: "us",
    baseUrl: "",
    apiFormat: "custom",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://modal.com/docs",
    pricing: "Serverless GPU: $0.000244/GPU-sec (A10G)",
    freeTier: true,
    status: "active",
    notes: "Serverless GPU. Run any model as a Python function. Scale to zero. Cold start optimization.",
    models: []
  },
  {
    name: "RunPod",
    slug: "runpod",
    category: "hosting",
    region: "us",
    baseUrl: "https://api.runpod.ai/v2",
    apiFormat: "custom",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.runpod.ai",
    pricing: "Serverless: $0.0002/GPU-sec + $0.00013/GB-hr",
    freeTier: false,
    status: "active",
    notes: "Best overall GPU cloud. Custom containers. Direct GPU access. Pod + Serverless. Scale to zero.",
    models: []
  },
  {
    name: "Baseten",
    slug: "baseten",
    category: "hosting",
    region: "us",
    baseUrl: "https://api.baseten.co/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.baseten.co",
    pricing: "Pay-per-use (Truss deployment)",
    freeTier: true,
    status: "active",
    notes: "High-performance model deployment. Truss framework. Autoscaling. Fast cold starts.",
    models: [
      { modelId: "llama-3.1-70b-instruct", modelName: "Llama 3.1 70B", contextWindow: 131072, maxOutput: 8192, pricing: "Contact for pricing", capabilities: ["chat"] },
    ]
  },
  {
    name: "Beam",
    slug: "beam",
    category: "hosting",
    region: "us",
    baseUrl: "",
    apiFormat: "custom",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://beam.cloud",
    pricing: "Serverless GPU from $0.0003/GPU-sec",
    freeTier: true,
    status: "active",
    notes: "Serverless GPU inference. Scale to zero. Fast cold starts. Python decorators.",
    models: []
  },
  {
    name: "Lambda Cloud",
    slug: "lambda-cloud",
    category: "hosting",
    region: "us",
    baseUrl: "",
    apiFormat: "custom",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://lambdalabs.com",
    pricing: "GPU instances from $0.75/hr (A10)",
    freeTier: false,
    status: "active",
    notes: "Budget GPU cloud. A100, H100, H200. 1-click Jupyter. On-demand + reserved.",
    models: []
  },

  // ===== CHINESE PROVIDERS =====
  {
    name: "Zhipu AI",
    slug: "zhipu",
    category: "chinese",
    region: "cn",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://open.bigmodel.cn/dev/api",
    pricing: '{"glm-4-plus":{"input":"¥50/百万token","output":"¥50/百万token"},"glm-4v-plus":{"input":"¥50/百万token","output":"¥50/百万token"}}',
    freeTier: true,
    status: "active",
    notes: "GLM-4 series. Vision support. Tool calling. Chinese + English bilingual. Free tokens for new users.",
    models: [
      { modelId: "glm-4-plus", modelName: "GLM-4 Plus", contextWindow: 128000, maxOutput: 4096, pricing: "¥50/¥50 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "glm-4v-plus", modelName: "GLM-4V Plus", contextWindow: 8192, maxOutput: 2048, pricing: "¥50/¥50 per Mtok", capabilities: ["chat", "vision"] },
    ]
  },
  {
    name: "Baichuan",
    slug: "baichuan",
    category: "chinese",
    region: "cn",
    baseUrl: "https://api.baichuan-ai.com/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://platform.baichuan-ai.com/docs",
    pricing: '{"baichuan4":{"input":"¥40/百万token","output":"¥40/百万token"}}',
    freeTier: true,
    status: "active",
    notes: "Baichuan 4. Chinese AI tiger. Medical, legal domain expertise. Open-source models.",
    models: [
      { modelId: "Baichuan4", modelName: "Baichuan 4", contextWindow: 128000, maxOutput: 4096, pricing: "¥40/¥40 per Mtok", capabilities: ["chat", "function_calling"] },
    ]
  },
  {
    name: "Moonshot AI (Kimi)",
    slug: "moonshot",
    category: "chinese",
    region: "cn",
    baseUrl: "https://api.moonshot.cn/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://platform.moonshot.cn/docs",
    pricing: '{"moonshot-v1-128k":{"input":"¥12/百万token","output":"¥12/百万token"}}',
    freeTier: true,
    status: "active",
    notes: "Kimi K3 (open-weight). 2M context window. Chinese AI tiger. Code, sheets, slides AI.",
    models: [
      { modelId: "kimi-k3-0725", modelName: "Kimi K3", contextWindow: 131072, maxOutput: 8192, pricing: "¥12/¥12 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "moonshot-v1-128k", modelName: "Moonshot V1 128K", contextWindow: 131072, maxOutput: 4096, pricing: "¥12/¥12 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "MiniMax",
    slug: "minimax",
    category: "chinese",
    region: "cn",
    baseUrl: "https://api.minimax.chat/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://www.minimaxi.com/document",
    pricing: '{"MiniMax-Text-01":{"input":"¥4/百万token","output":"¥16/百万token"}}',
    freeTier: true,
    status: "active",
    notes: "MiniMax-01 (MoE, open-weight). 4M context. Text + voice + video. 200M+ users globally.",
    models: [
      { modelId: "MiniMax-Text-01", modelName: "MiniMax-Text-01", contextWindow: 4194304, maxOutput: 8192, pricing: "¥4/¥16 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "01.AI",
    slug: "01ai",
    category: "chinese",
    region: "cn",
    baseUrl: "https://api.lingyiwanwu.com/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://platform.lingyiwanwu.com/docs",
    pricing: '{"yi-large":{"input":"¥20/百万token","output":"¥20/百万token"}}',
    freeTier: false,
    status: "active",
    notes: "Yi series (Yi-Lightning, Yi-Large). Kai-Fu Lee's company. Open-source Yi models. WorldWise enterprise platform.",
    models: [
      { modelId: "yi-lightning", modelName: "Yi-Lightning", contextWindow: 16384, maxOutput: 4096, pricing: "¥4/¥4 per Mtok", capabilities: ["chat"] },
      { modelId: "yi-large", modelName: "Yi-Large", contextWindow: 32768, maxOutput: 4096, pricing: "¥20/¥20 per Mtok", capabilities: ["chat", "function_calling"] },
    ]
  },
  {
    name: "Alibaba Tongyi Qianwen",
    slug: "tongyi-qianwen",
    category: "chinese",
    region: "cn",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "sk-",
    modelsUrl: "",
    docsUrl: "https://help.aliyun.com/zh/dashscope",
    pricing: '{"qwen-max":{"input":"¥40/百万token","output":"¥120/百万token"},"qwen-plus":{"input":"¥4/百万token","output":"¥12/百万token"}}',
    freeTier: true,
    status: "active",
    notes: "Qwen 2.5 / 3 series. Open-source (Qwen2.5-72B). OpenAI-compatible API via DashScope. VL, Audio, Math.",
    models: [
      { modelId: "qwen-max", modelName: "Qwen Max", contextWindow: 131072, maxOutput: 8192, pricing: "¥40/¥120 per Mtok", capabilities: ["chat", "vision", "function_calling"] },
      { modelId: "qwen-plus", modelName: "Qwen Plus", contextWindow: 131072, maxOutput: 8192, pricing: "¥4/¥12 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "qwen-vl-max", modelName: "Qwen VL Max", contextWindow: 131072, maxOutput: 8192, pricing: "¥40/¥120 per Mtok", capabilities: ["chat", "vision"] },
    ]
  },
  {
    name: "Baidu Ernie (Wenxin)",
    slug: "baidu-ernie",
    category: "chinese",
    region: "cn",
    baseUrl: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop",
    apiFormat: "custom",
    authType: "query",
    authHeader: "",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://cloud.baidu.com/doc/WENXINWORKSHOP",
    pricing: '{"ernie-4.0":{"input":"¥30/百万token","output":"¥30/百万token"}}',
    freeTier: true,
    status: "active",
    notes: "ERNIE 4.0/4.0 Turbo. Baidu search integration. Plugin ecosystem. Chinese-optimized.",
    models: [
      { modelId: "ernie-4.0-8k", modelName: "ERNIE 4.0", contextWindow: 8192, maxOutput: 4096, pricing: "¥30/¥30 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "ernie-4.0-turbo-8k", modelName: "ERNIE 4.0 Turbo", contextWindow: 8192, maxOutput: 4096, pricing: "¥12/¥12 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "Volcengine (Doubao)",
    slug: "volcengine",
    category: "chinese",
    region: "cn",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://www.volcengine.com/docs/82379",
    pricing: '{"doubao-pro-32k":{"input":"¥5/百万token","output":"¥9/百万token"}}',
    freeTier: true,
    status: "active",
    notes: "Doubao (Doubao-pro, Doubao-lite). ByteDance's LLM. Very cheap. High throughput.",
    models: [
      { modelId: "doubao-pro-32k", modelName: "Doubao Pro 32K", contextWindow: 32768, maxOutput: 4096, pricing: "¥5/¥9 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "StepFun",
    slug: "stepfun",
    category: "chinese",
    region: "cn",
    baseUrl: "https://api.stepfun.com/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://platform.stepfun.com/docs",
    pricing: '{}',
    freeTier: true,
    status: "active",
    notes: "Step-1/Step-2 models. Emerging Chinese AI startup. OpenAI-compatible API.",
    models: [
      { modelId: "step-1-8k", modelName: "Step-1 8K", contextWindow: 8192, maxOutput: 4096, pricing: "Contact for pricing", capabilities: ["chat"] },
    ]
  },
  {
    name: "iFlytek (Spark)",
    slug: "iflytek",
    category: "chinese",
    region: "cn",
    baseUrl: "https://spark-api-open.xf-yun.com/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://www.xfyun.cn/doc/spark",
    pricing: '{}',
    freeTier: true,
    status: "active",
    notes: "Spark 4.0 Ultra. Speech + text multimodal. Chinese education/enterprise focus.",
    models: [
      { modelId: "spark-4.0-ultra", modelName: "Spark 4.0 Ultra", contextWindow: 131072, maxOutput: 4096, pricing: "Contact for pricing", capabilities: ["chat"] },
    ]
  },

  // ===== KOREAN / JAPANESE / INDIAN =====
  {
    name: "Upstage",
    slug: "upstage",
    category: "asian",
    region: "kr",
    baseUrl: "https://api.upstage.ai/v1/solar",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://developers.upstage.ai/docs",
    pricing: '{"solar-pro":{"input":"$0.6/mtok","output":"$1.2/mtok"},"solar-mini":{"input":"$0.1/mtok","output":"$0.1/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "Solar Pro / Solar Mini. Korean startup. Document understanding (Grounded RAG). English + Korean.",
    models: [
      { modelId: "solar-pro", modelName: "Solar Pro", contextWindow: 131072, maxOutput: 4096, pricing: "$0.6/$1.2 per Mtok", capabilities: ["chat", "function_calling"] },
      { modelId: "solar-mini", modelName: "Solar Mini", contextWindow: 131072, maxOutput: 4096, pricing: "$0.1/$0.1 per Mtok", capabilities: ["chat"] },
    ]
  },
  {
    name: "Naver",
    slug: "naver",
    category: "asian",
    region: "kr",
    baseUrl: "https://clovachatx.ncloud.com/ncp/clovachatx/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://guide.ncloud-docs.com/docs/clova-chat",
    pricing: "Naver Cloud pricing",
    freeTier: false,
    status: "active",
    notes: "HyperCLOVAX. Naver's enterprise LLM. Korean-optimized. Naver Cloud Platform.",
    models: [
      { modelId: "hcX-005", modelName: "HyperCLOVAX", contextWindow: 4096, maxOutput: 2048, pricing: "Naver Cloud pricing", capabilities: ["chat"] },
    ]
  },
  {
    name: "Sarvam AI",
    slug: "sarvam",
    category: "asian",
    region: "in",
    baseUrl: "https://api.sarvam.ai/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.sarvam.ai",
    pricing: '{}',
    freeTier: true,
    status: "active",
    notes: "Indian LLM startup. Sarvam-1, Sarvam-2. Indic languages support. Voice + text AI.",
    models: [
      { modelId: "sarvam-2b", modelName: "Sarvam 2B", contextWindow: 8192, maxOutput: 2048, pricing: "Free tier", capabilities: ["chat"] },
    ]
  },
  {
    name: "Krutrim AI",
    slug: "krutrim",
    category: "asian",
    region: "in",
    baseUrl: "https://api.krutrim.com/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.krutrim.ai",
    pricing: '{}',
    freeTier: true,
    status: "active",
    notes: "Ola's AI division. Multilingual Indian LLM. Supports 20+ Indian languages.",
    models: [
      { modelId: "krutrim-2b", modelName: "Krutrim 2B", contextWindow: 4096, maxOutput: 2048, pricing: "Free tier", capabilities: ["chat"] },
    ]
  },
  {
    name: "Rakuten AI",
    slug: "rakuten",
    category: "asian",
    region: "jp",
    baseUrl: "",
    apiFormat: "custom",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://ai.rakuten.com",
    pricing: "Contact for pricing",
    freeTier: false,
    status: "active",
    notes: "Japanese LLM. Rakuten's internal AI. Japanese-optimized. Limited public API.",
    models: []
  },

  // ===== EMERGING / SPECIALTY =====
  {
    name: "Writer",
    slug: "writer",
    category: "emerging",
    region: "us",
    baseUrl: "https://api.writer.com/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://dev.writer.com/docs",
    pricing: '{}',
    freeTier: false,
    status: "active",
    notes: "Palmyra models. Enterprise content generation. RAG-first. Graph-based knowledge.",
    models: [
      { modelId: "palmyra-x-004", modelName: "Palmyra X 004", contextWindow: 131072, maxOutput: 4096, pricing: "Enterprise pricing", capabilities: ["chat", "function_calling"] },
    ]
  },
  {
    name: "Reka AI",
    slug: "reka",
    category: "emerging",
    region: "us",
    baseUrl: "https://api.reka.ai/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.reka.ai",
    pricing: '{}',
    freeTier: true,
    status: "active",
    notes: "Reka Core / Reka Flash / Reka Edge. Multimodal (text, image, video, audio). Fast inference.",
    models: [
      { modelId: "reka-core", modelName: "Reka Core", contextWindow: 131072, maxOutput: 4096, pricing: "$10/$10 per Mtok", capabilities: ["chat", "vision"] },
      { modelId: "reka-flash", modelName: "Reka Flash", contextWindow: 131072, maxOutput: 4096, pricing: "$0.8/$0.8 per Mtok", capabilities: ["chat", "vision"] },
    ]
  },
  {
    name: "Inflection AI",
    slug: "inflection",
    category: "emerging",
    region: "us",
    baseUrl: "",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://inflection.ai",
    pricing: "Free (consumer) / Enterprise",
    freeTier: true,
    status: "active",
    notes: "Inflection 3.0 (Pi). Emotional intelligence. Now enterprise-focused. White-label solutions.",
    models: [
      { modelId: "inflection-3.0", modelName: "Inflection 3.0", contextWindow: 32768, maxOutput: 2048, pricing: "Free tier", capabilities: ["chat"] },
    ]
  },
  {
    name: "Aleph Alpha",
    slug: "aleph-alpha",
    category: "emerging",
    region: "eu",
    baseUrl: "https://api.aleph-alpha.com",
    apiFormat: "custom",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.aleph-alpha.com",
    pricing: "European enterprise pricing",
    freeTier: false,
    status: "active",
    notes: "Luminous models. European AI. GDPR-compliant. Sovereign AI. On-prem deployment.",
    models: [
      { modelId: "luminous-extended", modelName: "Luminous Extended", contextWindow: 8192, maxOutput: 2048, pricing: "Enterprise pricing", capabilities: ["chat", "vision"] },
    ]
  },
  {
    name: "Ollama Cloud",
    slug: "ollama-cloud",
    category: "emerging",
    region: "us",
    baseUrl: "https://api.ollama.ai/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://github.com/ollama/ollama",
    pricing: "Open-source / Cloud pricing TBD",
    freeTier: true,
    status: "active",
    notes: "Popular local LLM runner. Cloud API emerging. 100K+ models on library. llama.cpp based.",
    models: [
      { modelId: "llama3.1", modelName: "Llama 3.1", contextWindow: 131072, maxOutput: 4096, pricing: "Free (local)", capabilities: ["chat"] },
    ]
  },
  {
    name: "AI/ML API",
    slug: "aimlapi",
    category: "emerging",
    region: "us",
    baseUrl: "https://api.aimlapi.com/v1",
    apiFormat: "openai",
    authType: "bearer",
    authHeader: "Authorization",
    keyPrefix: "",
    modelsUrl: "",
    docsUrl: "https://docs.aimlapi.com",
    pricing: '{"mixtral-8x7b":{"input":"$0.3/mtok","output":"$0.3/mtok"}}',
    freeTier: true,
    status: "active",
    notes: "100+ models. OpenAI-compatible. Cheap alternative. Text + image + audio.",
    models: [
      { modelId: "mixtral-8x7b-instruct", modelName: "Mixtral 8x7B", contextWindow: 32768, maxOutput: 4096, pricing: "$0.3/$0.3 per Mtok", capabilities: ["chat"] },
    ]
  },
];

// Existing NeoGateway providers (excluded from discovery)
export const existingNeoGatewayProviders = [
  { slug: "aion", name: "AIon", prefix: "sk-" },
  { slug: "cloudflare-ai", name: "Cloudflare Workers AI", prefix: "<token>" },
  { slug: "cohere", name: "Cohere", prefix: "..." },
  { slug: "gemini", name: "Google Gemini", prefix: "AIza..." },
  { slug: "kilo-gateway", name: "Kilo Gateway", prefix: "..." },
  { slug: "mistral", name: "Mistral AI", prefix: "..." },
  { slug: "nvidia", name: "NVIDIA NIM", prefix: "nvapi-..." },
  { slug: "openrouter", name: "OpenRouter", prefix: "sk-or-..." },
  { slug: "sambanova", name: "SambaNova", prefix: "..." },
  { slug: "siliconflow", name: "SiliconFlow", prefix: "sk-..." },
  { slug: "deepseek", name: "DeepSeek", prefix: "sk-..." },
];

export const categoryColors: Record<string, string> = {
  "first-party": "bg-rose-500/10 text-rose-600 border-rose-500/20",
  "inference": "bg-emerald-500/10 text-emerald-600 border-emerald-500/20",
  "gateway": "bg-amber-500/10 text-amber-600 border-amber-500/20",
  "cloud": "bg-sky-500/10 text-sky-600 border-sky-500/20",
  "chinese": "bg-red-500/10 text-red-600 border-red-500/20",
  "asian": "bg-violet-500/10 text-violet-600 border-violet-500/20",
  "hosting": "bg-orange-500/10 text-orange-600 border-orange-500/20",
  "emerging": "bg-teal-500/10 text-teal-600 border-teal-500/20",
};

export const regionLabels: Record<string, string> = {
  "us": "🇺🇸 US",
  "eu": "🇪🇺 EU",
  "cn": "🇨🇳 China",
  "kr": "🇰🇷 Korea",
  "jp": "🇯🇵 Japan",
  "in": "🇮🇳 India",
  "global": "🌐 Global",
};
